Refactoring docker build and push
tubiomics/vulcan pull request #15
Opened 2023-01-31 00:39 UTC by tjyacoub

Using the following command we can create the docker push yaml file for all of the folders (recursively) in the `docker/` folder.

python3 create-push-yaml.py -dockerfile_paths all

It can also be run with specific folders to create a yaml file for only those folders:

python3 create-push-yaml.py -dockerfile_paths docker/binning docker/

2023-01-31 00:44 UTC, tjyacoub commented
Wrote python script to generate YAML file for docker build and push based on dockerfile paths 

Further steps in refactoring docker codebase:

1. Integrate python script into Makefile
2. Delete unused images
3. Build and push all remaining 
4. Pull only the used images from dockerhub
5. Integrate pull command into Makefile

2023-01-31 18:42 UTC, spitfiredd requested changes
Can you remove `.github/workflows/push-image-dockerhub-orig.yaml` file.  

There are also more nextflow processes we need to update, e.g. `modules/vamb/variational_autoencode.nf`

2023-01-31 21:31 UTC, tjyacoub commented
Ok I took care of those, should be ready for approval and merge

> Can you remove `.github/workflows/push-image-dockerhub-orig.yaml` file.
> 
> There are also more nextflow processes we need to update, e.g. `modules/vamb/variational_autoencode.nf`

2023-02-01 16:49 UTC, spitfiredd approved these changes

2023-02-01 16:49 UTC, merged